### ISSUE TITLE
GMSK mod/demod cleanup

### ISSUE THREAD

**Issue by n-west** [gnuradio/gnuradio#1103]
The digital.gmsk_mod block has high functionality and code overlap with analog.cpm_mod. Consider replacing the existing implementation with a thin wrapper around analog.cpm_mod. If this is done we can either keep the gmsk_demod hierblock or move a GMSK loopback in to an example.

Depending on the action taken with gmsk_demod this does not necessarily require an API change because gr-digital which holds gmsk.py already depends on gr-analog.

This has been brought up as part of 3.8 clean up with a weak recommendation to replace the existing implementation for code deduplication.

**Comment by marcusmueller** [comment]
We'll have to merge all these *_mod issues into one large "decruftify modulators" one, and check the current state of things. It's not realistic that we'll remove any of these in 3.11 (if that ever happens), so I'll close the others and mark this as "Needs reproduction" because I don't even know the state of things, and should really coordinate with @mormj and @willcode whether this is still something we want to tackle.
