### ISSUE TITLE
WX GUI support broken in Wayland (Fedora 25)

### ISSUE THREAD

**Issue by phocean** [gnuradio/gnuradio#1151]
I am using Fedora 25 which defaults to Wayland in replacement of Xorg.
GRC 3.7.10.1.

Support for WX GUI is broken: building seems to work fine but it terminates immediately without  any error message: nothing got executed, no window appear.

QT GUI keeps working fine.

If I open a X11 session, then WX GUI works as expected.

**Comment by jmcorgan** [comment]
It's unfortunate that this is the case.  However, the WXGUI feature set in GNU Radio is deprecated and has been removed for our next API release (3.8).  We strong recommend you port your applications to the QT-based window system support.

If it turns out the solution to this is a simple fix, and someone submitted a patch, we'd consider merging it into our final 3.7 API release. Otherwise, this issue won't be addressed.
