### ISSUE TITLE
How to make QT GUI Entry module support Chinese？

### ISSUE THREAD

**Issue by bighold** [gnuradio/gnuradio#1532]
I make a change on qtgui_entry_xml. As bellow：

  `24 lambda: self.set_$(id)($(type.conv)(str(self._$(id)_line_edit.text().toLocal8Bit()))))<!--change toAscii to toLocal8Bit-->`
![display](https://user-images.githubusercontent.com/32125232/33157956-f7117ff0-d040-11e7-9dbe-f9f51b28c5b4.png)

  Now I type in Chinese in the entry box of the Entry module. But after typing Enter, the Chinese in the input box will become garbled. But one of my display modules correctly displays the Chinese sent by the Entry module. Therefore, the question is how to ensure that the input box of the Entry module does not occur garbled.
![display](https://user-images.githubusercontent.com/32125232/33157902-a36e0cf6-d040-11e7-80eb-8c7a8031a697.png)
![entry](https://user-images.githubusercontent.com/32125232/33157904-a8674a88-d040-11e7-8d9b-bd74627d8e6e.png)

**Comment by jasonuher** [comment]
I think the move to python3 may have fixed this.  I believe the correct method for solving this issue was to ensure the text string was utf8 encoded prior to the call to 'str' (which happens by default in python3).  Here's my screenshot of the same scenario (well.. 中国 instead of 中人 in the original screenshot but...).  

A few thoughts:
- I'm not sure what the original motivation was for adding the "toLocal8bit" but I don't think that's necessary here
- Maybe this is a maint-3.8 issue only now?
- Maybe it depends on which language packs are installed though, too...?

(The attached flow graph is just a "qt gui entry" and a "qt gui label" linked to the same variable)

![2021-02-22-214338_240x148_scrot](https://user-images.githubusercontent.com/6929725/108796645-3105cb80-7557-11eb-820d-0333a61ca8c3.png)

**Comment by marcusmueller** [comment]
It's supported! I was really upset at some point that I couldn't use my last name in a field…
