### ISSUE TITLE
What replaces blks2.tcp_source block?

### ISSUE THREAD

**Issue by regulatre** [gnuradio/gnuradio#1540]
"Warning: the blks2.tcp_source block is deprecated"

But what replaces this functionality?

Any link to why it is being deprecated?

Thanks!

**Comment by marcusmueller** [comment]
I'd like to ask you to rename this issue to 

> Unclear replacement of blks2.tcp_source (feature regression)

As it's phrased now, it is a *question*, but this is a *bug tracker*, so that doesn't fit overly well here :) For future questions, please try our [mailing list](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio).

Regarding as to why: It's a pile of bad code. Its constructor blocks until a connection is made, which is a big no-go in a real application (because then you can't even construct your flow graph until someone else connected to your TCP port, and that's simply a bad design decision). Also, the whole blks2 hierarchy has to go (as it's really made of legacy python code from the early days of GRC, when people weren't so sure where to put their code.
