### ISSUE TITLE
Soft bit calculation of constellation is not AWGN based?

### ISSUE THREAD

**Issue by lleoha** [gnuradio/gnuradio#1607]
More of a question than issue but I don't understand why in method `constellation::calc_soft_dec` we have
`        // Calculate the distance between the sample and the current`
`        // constellation point.`
`        float dist = std::abs(sample - d_constellation[i]);`
`        // Calculate the probability factor from the distance and`
`        // the scaled noise power.`
`        float d = expf(-dist/npwr);`

IMO (given AWGN channel) it should be:
`float dist = std::abs(sample - d_constellation[i]);`
`float d = expf(-dist*dist/npwr);`

Is my understanding correct?

**Comment by marcusmueller** [comment]
For reference:

https://github.com/gnuradio/gnuradio/blob/v3.7.11/gr-digital/lib/constellation.cc#L282-L310

What difference would that make?

What's done with `d` is 

```c++
          // If the bit is a 0, add to the probability of a zero
          if(bit == 0)
            tmp[2*j+0] += d;
          // else, add to the probability of a one
          else
            tmp[2*j+1] += d
```
Now, I haven't actually done the math on this all the way down to where the LLRs are used, but:

isn't the whole LLR business possible because the logarithm is a strictly monotonic thing on anything that could be a sum of probabilities? Wouldn't dist² still be a monotonic operation and hence, not change the ordering of LLRs?

**Comment by mbr0wn** [comment]
As we're trying to clear up the issue tracker, and this is more a question than anything else, I'm closing this. Please continue the conversation on Chat, or on the mailing list!
