### ISSUE TITLE
GRC embedded Python blocks don't work anymore

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#1666]
When an embedded Python block is added to a GRC flowgraph, the following error appears:
```
Param - Code(_source_code):
	'py_io_signature' object is not iterable
```
It seems there is no way to resolve the error.

I suspect the issue is related to ba63bd46e3a79d4312a16d9d35f918aa4cfa67db; GRC probably needs to be updated to use the new IO signature format.

@willcode

**Comment by willcode** [comment]
Yes, most likely my fault - I haven't used Python blocks from GRC and 
didn't consider that. I'll take a look at it.

**Comment by marcusmueller** [comment]
Thanks, @willcode, and thanks @argilo for reporting.

**Comment by marcusmueller** [comment]
The culprit seems to be in `epy_block_io.py`'s `_ports()`:

```python
def _ports(sigs, msgs):
    ports = list()
    for i, dtype in enumerate(sigs):
…
```

**Comment by marcusmueller** [comment]
@willcode gut feeling, adding a quick 

```python
    def __iter__(self):
        return self
    def next(self):
         for elem in self.__types:
             yield elem
```

to your py_io_signature could help!

**Comment by marcusmueller** [comment]
No, wait, I don't like that. That way, an instance can only be iterated through once.

Instead
```python
def __iter__(self):
     return iter(self.__types)
```

would be both simpler and smarter.

**Comment by willcode** [comment]
This fix seems to work, until we can find a way to teach GRC about 
Python blocks with a variable number of ports. In the mean time, it will 
assume num i/o is equal to the number of types.

Marcus, since it's just a couple lines, would you like to put this in 
yourself? I'll think about how to make GRC ask for number of 
inputs/outputs correctly when I get some time.

**Comment by marcusmueller** [comment]
@willcode I will do that.

**Comment by marcusmueller** [comment]
Calling @skoslowski on this, because that's an architectural aspect of GRC, and chances are that he's already considered this, so that @willcode doesn't need to :)

**Comment by willcode** [comment]
Good idea. The problem is that GRC usually controls the blocks, using 
xml files for hints, but for the Python block it uses introspection. So, 
no component actually knows how many ports the user wants.

The solution is probably to have GRC detect whether there is a variable 
number of ports (via introspection) just as it would get that info from 
an xml file, then add num inputs/outputs to the dialog.

**Comment by skoslowski** [comment]
You are correct. I can have a closer look later this week.
If you want to take a stab at this, let me know.
