### ISSUE TITLE
gr_unittest does not support skip()

### ISSUE THREAD

**Issue by m3x1m0m** [gnuradio/gnuradio#1677]
https://github.com/gnuradio/gnuradio/blob/da0a102e9b076db83fe5a63b3730ac39b588eb92/gnuradio-runtime/python/gnuradio/gr_unittest.py

I think a skip command as can be found in unittest might be useful. 

https://docs.python.org/3.5/library/unittest.html#skipping-tests-and-expected-failures

**Comment by jdemel** [comment]
Python `unittest` provides [skip](https://docs.python.org/2/library/unittest.html) (compare Sec 25.3.6). The `TestCase` in `gr_unittest.py` inherits from `unittest.TestCase`. As such it should come with the same functionality.
GR does not necessarily rely on Python 2.7. But GR3.8 will arguably expect Python versions that provide `skip`. Thus, I'd suggest to close this issue because GR inherits or will inherit this behavior.
