### ISSUE TITLE
Gnuradio Next Branch installation crashes on inserting certain componenets

### ISSUE THREAD

**Issue by jabirshabbir** [gnuradio/gnuradio#1732]
Hi,
I have installed gnuradio by building the next branch.It crashes when I insert certain GUI blocks such QT GUI Time Sink,QT GUI Vector Sink or any of the QT GUI sink components.Is it that the QT component is incorrectly build? Or some library is missing for building QT component,although it says that Dependency QT_FOUND = 1 while during cmake

**Comment by jabirshabbir** [comment]
There is a substitute for Qt GUI which is WX-GUI but I could find this component in next branch source.

**Comment by marcusmueller** [comment]
Wx is no longer an alternative. It's being removed from GNU Radio. QT_FOUND=1 is necessary, but not sufficient for enabling qtgui. You'll have to read the cmake output very carefully.

As this is, at this point, this is most likely just a missing dependency, and not a GNU Radio bug, so I'm closing this issue.

If it turns out this is really indeed a bug, will just reopen.
