### ISSUE TITLE
CMake can't find QWT on Arch Linux

### ISSUE THREAD

**Issue by haakov** [gnuradio/gnuradio#2208]
It looks like the Linux distributions' name for qwt-qt5 vary a bit. From what I can tell, https://github.com/gnuradio/gnuradio/commit/d4225d6add2bda7e865e00aee31a57770336fa4b was intended to fix this, but `PC_QWT_LIBRARIES` seems to be just an empty string on my end.

I am able to get it to build by appending "`qwt`" to the `NAMES`.

CMake output:
```
(...)
-- Found PythonLibs: /usr/lib/libpython3.7m.so (found suitable version "3.7.1", minimum required is "2") 
-- Python checking for PyQt5 - found
-- Checking for module 'Qt5Qwt6'
--   Package 'Qt5Qwt6', required by 'virtual:world', not found
-- QWT Version: 6.1.3
-- Could NOT find Qwt (missing: QWT_LIBRARIES)
(...)
```

Packages and libraries:

```
$ pacman -Ss qwt
extra/qwt 6.1.3-4 [installed]
Qt Widgets for Technical Applications
community/qwt5 5.2.3-5 [installed]
Qt Widgets for Technical Applications (version 5.X)
```

```
$ ls /usr/lib | grep qwt
libqwt5.so
libqwt5.so.1
libqwt5.so.1.0
libqwt5.so.1.0.0
libqwt.so
libqwt.so.6
libqwt.so.6.1
libqwt.so.6.1.3
```

**Comment by noc0lour** [comment]
I actually checked beforehand and saw that ArchLinux might be a problem. I think the packageconfig PR can help with that?

**Comment by michaelld** [comment]
I have a similar issue on OSX: the PC info isn't correct (lies! all lies!!) ... and so the FindQwt.cmake script either fails to find a useful Qwt (now version 6), or it finds conflicting API / ABI. I always just overload the correct CMake variables so that the version of Qwt that I want CMake to find is found. I recognize that this build style won't work for everyone, but also that there is no way that we can list/name very single possible Qwt library naming variant used by various OS distributions. We trust to some degree that when a project installs a PC file it is providing correct information; when it doesn't we can only do so much.

**Comment by noc0lour** [comment]
Hm, yeah, the library/distro should have clean PC configuration if they ship one. Probably should be filed either upstream or for each distribution this fails.

**Comment by doronbehar** [comment]
I can confirm this problem no longer exists in the latest master branch.

**Comment by haakov** [comment]
Was this fixed? Looks the same to me

**Comment by noc0lour** [comment]
Oh, ok. I'll reopen.

**Comment by mbr0wn** [comment]
I think we had to remove qwt from NAMES because it was impossible to distinguish qt4 and qt5 versions in that case.

**Comment by nickoe** [comment]
It looks like the AUR package for gnuradio-git solves with by adding this cmake argument:
`-DQWT_LIBRARIES=/usr/lib/libqwt.so`

**Comment by noc0lour** [comment]
Only PyQwt is going away, regular Qwt is meant to stay. But probably this can be closed with the workaround for ArchLinux Users to specify libQwt.so on the commandline until all the Qt4 Qwt is gone.

**Comment by nickoe** [comment]
For the record `-DQWT_LIBRARIES=/usr/lib/libqwt.so` is needed on arch to make the gnuradion cmake script enable `gr-qtgui`.

**Comment by robincoxe** [comment]
A variant of this issue appears to be lingering.  I encountered it just now on a Ubuntu 18.04 system for GNU Radio versions newer than v3.7.13.5.  adding the -DQWT_libraries argument doesn't help.  

-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.8", minimum required is "2") 
-- Python checking for PyQt5 - found
-- Checking for module 'Qt5Qwt6'
--   No package 'Qt5Qwt6' found
-- QWT Version: 6.1.3
-- Found Qwt: /usr/lib/libqwt.so

**Comment by vinbo** [comment]
> For the record `-DQWT_LIBRARIES=/usr/lib/libqwt.so` is needed on arch to make the gnuradion cmake script enable `gr-qtgui`.

this works for the built, but i cannot run the node.
Segmentation fault (core dumped)

**Comment by sv1ple** [comment]
I faced the Segmentation fault issue in GNU Radio v3.8.0.0 (in Ubuntu 16.04 system though).
I used -DQWT_LIBRARIES=/usr/lib/libqwt-qt5.so and the segmentation fault stopped, based on the last reply in this [link](http://answers.gazebosim.org/question/15348/gazebo-client-on-debian-crashes-at-startup/
).

**Comment by btashton** [comment]
This is also an issue on Fedora 30.  @marcusmueller I don't think PR  #2756 should have been merged in just because Arch is not playing nicely and using libqwt to refer to libqwt-qt5.

**Comment by michaelld** [comment]
I'll 2nd @btashton and @mbr0wn 's comments: let's revert #2756 ... if Arch wants their own special ABI naming, they can use `-DQWT_LIBRARIES=...` to get that naming for GR's needs.

**Comment by FFY00** [comment]
@btashton @michaelld that is absolutely wrong. Arch does not modify any namespace. The upstream soname is `libqwt.so`, not `libqwt-qt5.so`. Arch is not the one not playing nicely, other distros are actively changing the upstream name and, as so, they have to deal with it.

Distributions like fedora patch the `qwt` soname to `libqwt-qt5.so` because they want to keep Qt4 the default, and they're welcome to do it, but they have to deal with that.

This project requires Qwt built with Qt5, and the upstream soname is `libqwt.so`. This is name should be honered. If your distribution wants to provide you with an alternative Qwt installation built with Qt 5 in an alternative namespace, you are the one that should set `QWT_LIBRARIES`.

**Comment by btashton** [comment]
I never said arch was doing something "wrong" just that we cannot detect the version of qt it was built with. With other distros we can because they do modify it in a detectable way (i suspect this is why they do it in the first place). The arch package already knows that it has QT5 so it can just set this in the recipe.  Same for devs doing builds.  If libqwt had a symbol that reflected what it was built against that would also work, but this is not an option.

**Comment by FFY00** [comment]
Sorry for my bluntness but let me quote you:

> don't think PR #2756 should have been merged in just because Arch is not playing nicely and using libqwt to refer to libqwt-qt5

Here you imply that arch is doing something wrong.

The Qwt upstream does not provide a way to detect which Qt version is used. That's why distributions just do their thing, and it's a mess. Debian calls it `libqwt5.so`, Fedora `libqwt-qt5.so`, etc. They are all patching the upstream name. The GNU Radio project should be stay impartial and use the name the Qwt upstream chooses.

So, no. The PR should definitely not be reverted.

**Comment by michaelld** [comment]
2 thoughts from me:

(1) the commit has not been reverted, and I think there is no active effort to do so. In the interim, I know of no complaints about it's change impacting anyone. Maybe I'm not enough in the loop here?

(2) The CMake script for FindQwt is here, and it is -overall- what is important, not just this one change: < https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/FindQwt.cmake >

It is important that the `QWT_INCLUDE_DIRS/qwt_global.h` has the correct VERSION info ... and, this is checked for in the find script.

What's not checked for is whether the `QWT_LIBRARIES` corresponds to the `QWT_INCLUDE_DIRS` ... but this is a common issue with CMake find script .. not something we are going to fix.

Hence, since the change in #2756 adds `qwt` as the -last- library name to check, and has been active for a few months now without issues (TTBOMK): I'm actually OK with it in combination with the other checks being done.

**Comment by btashton** [comment]
> The Qwt upstream does not provide a way to detect which Qt version is used. That's why distributions just do their thing, and it's a mess. Debian calls it `libqwt5.so`, Fedora `libqwt-qt5.so`, etc. They are all patching the upstream name. The GNU Radio project should stay impartial and use the name the Qwt upstream choose.

But in practice they do this because, as we have seen, people run into issues where bad builds are created. I would rather have the build fail and say hey here is the issue if you know you have libqwt.so then add this flag instead of continuing to get bugs where soon as qwt library is called the whole thing segfaults.  

It's great that Arch is able to just have one version of the library, I wish Fedora and others would be in the same place.  Having the Arch recipe add a single flag to the build seemed like a compromise that reduced silent bad builds for other major architectures.
