### ISSUE TITLE
GRC does not show variable names

### ISSUE THREAD

**Issue by fmagno** [gnuradio/gnuradio#2585]
`GR version: v3.8-MacPorts-next-git-8a7214c7(20190521-8a7214c7) (Python 2.7.16)`

gnuradio-companion does not show variable name inside the variable block. It can be confusing when dealing with flowgraphs with many variables.

![image](https://user-images.githubusercontent.com/3079603/60385102-8c7b6f80-9a7d-11e9-8ac6-e3fe0161e887.png)

**Comment by bastibl** [comment]
Can you please update GNU Radio and try again (if I understand the build description correctly, you are using the GNU Radio version from 14 May).  There was an issue about the problem (https://github.com/gnuradio/gnuradio/issues/2235) and it should be fixed in the most recent version (https://github.com/gnuradio/gnuradio/pull/2568).

**Comment by fmagno** [comment]
OK, thanks. I'll give it a try as soon as I can. For now it seems wise just to close this issue.
