### ISSUE TITLE
GRC color scheme help

### ISSUE THREAD

**Issue by na0b** [gnuradio/gnuradio#2687]
I am running GRC on a Live Linux Parrot OS distribution. Many of the text colors are messed up. When editing a block, sometimes the text and the background are of the same color, so you cannot see what you are writing. While I am able to change colors in other applications, nothing seems to work for GRC.
Can someone point me in the right direction?
Thanks,
Juan.

**Comment by mormj** [comment]
Would you be able to post a screenshot to give a better idea what you are seeing?

**Comment by na0b** [comment]
OK.Here is a screen capture. In the ID field of the Variable block, both the text and the background are set to the same color. Thanks.

![grccolorscheme](https://user-images.githubusercontent.com/4021714/62180574-243ada80-b316-11e9-953e-f22b18bdf53f.png)

**Comment by mormj** [comment]
Hmmm .. does changing your color scheme in your linux distro have any effect?

**Comment by na0b** [comment]
This is not the case  with the Parrot distro. I  also posted a question at the Parrot community, but received no answer. I will go back to Ubuntu. Thanks.
What I think would be very useful to schools is a lean live GNURadio distro with networking. If you  know of any, please let me know.

**Comment by cbdonohue** [comment]
You can change the theme in Parrot OS by going to System -> Look and Feel -> Appearance. Then try a theme like "TraditionalOK" and you should be able to see everything in gnuradio. 
![Screenshot from 2019-10-31 14-29-47](https://user-images.githubusercontent.com/1757340/67975790-264d5780-fbeb-11e9-8d2e-020f1b33cac4.png)

**Comment by nlitsme** [comment]
I noticed that I needed to change my OS color scheme from dark to standard, and then back to dark.
Now the foreground text color in GRC changed from white ( unreadable ) to black ( ok ).
While also retaining the general scheme I like for the rest of my apps.

But since GRC is the first app I found which seems to make a wrong choice by default for the text color, I think the problem may be with GRC.

I am running a kde/plasma desktop on debian.

willem

**Comment by cafeclimber** [comment]
I honestly think that's clearer in the long term at least for the GTK version. I personally never even made the connection between the colors and the parameter's type 😅 For Qt, I know you can have different validators on the various fields

**Comment by marcusmueller** [comment]
connections between colors and types: me neither, the pastel goth version of the in/output port colors just doesn't strike me as too significant, and also, there's no "string" input port, and reserving anything reddish for "invalid" seems just right…

**Comment by marcusmueller** [comment]
That's not bad, and should you have already coded this: I'd advocate we try it, see how people using `main` like it, because it's already much better (imho) than the staus quo, though I'd have gone for more of a tabular approach, with an illustrative third column in that layout

|  |   |   |
|---|---|---|
| Max Number of Output | `[ Text entry field ]` | ℤ integer |
| Author | `[ Text entry field ]` | A…Z string |
| Height of Respect | `[ Text entry field ]` | ℝ float |
| Wave number | `[ Text entry field ]` | ℂ complex |
| Favorite Monarch | `[ Count von Count ▾ ]` | choice |
| Rage against the Machine | `[ On ▾ ]`  | ✓✗boolean |
| QSS Theme | `[ text field ] [File selector btn]` | 📂 File for reading |


(also, while I'm looking at dialogs… can we not center-align the labels?)

**Comment by cafeclimber** [comment]
Yeah this was a very simple edit of a couple lines. Splitting into three columns shouldn't be too difficult? And I'm happy to switch to left-aligned lol

**Comment by chrboesch** [comment]
@cafeclimber Thanks, that helps me a lot! :smile:

**Comment by willcode** [comment]
Addressed by #6888 #6911
