### ISSUE TITLE
Unexpected behavior of grcc with --output for hier blocks

### ISSUE THREAD

**Issue by bgottula** [gnuradio/gnuradio#2799]
The behavior of the `--output` option of `grcc` is inconsistent with the documentation when `grcc` is run on a GRC hier block. Specifically, even when a path is supplied to `--output`, `grcc` ignores the path provided and proceeds to write the generated .py and .yml files to HIER_BLOCK_LIB_DIR (~/.grc_gnuradio by default) anyway.

Usage info for `--output` does not mention any exceptions:
```
  -o DIR, --output DIR  Output directory for compiled program [default=.]
```

The source code is also misleading. A `file_path` is provided to the constructor of `HierBlockGenerator`, with [doctring](https://github.com/gnuradio/gnuradio/blob/master/grc/core/generator/hier_block.py#L22)
```
file_path: where to write the py file (the yml goes into HIER_BLOCK_LIB_DIR)
```
But the source code of the constructor actually clobbers `file_path` with `hier_block_lib_dir` on [this line](https://github.com/gnuradio/gnuradio/blob/master/grc/core/generator/hier_block.py#L32):
```
self.file_path = os.path.join(hier_block_lib_dir, self._flow_graph.get_option('id') + '.py')
```

Personally I'd prefer to be able to set the output path of GRC for both the .py file and the .yml file with command line arguments as an alternative to using the HIER_BLOCK_LIB_DIR environment variable. But even if this is not possible the documentation should be updated to clarify the fact that `--output` is ignored for hier blocks.

**Comment by jaredd** [comment]
Yes, I just ran into this myself on the maint-3.8 branch. It appears this is still an issue on master. One commit that appears to be part of the issue is f25f0c573a519babd3bc6099230177cdd022ecdd which removes the `file_path` parameter in [HierBlockGenerator](https://github.com/gnuradio/gnuradio/commit/f25f0c573a519babd3bc6099230177cdd022ecdd#diff-7656238266b046810186088ee826bacbbc2ffbbb7571ef3e3f49bb21744dfef2L12-L22). That commit seems to have to do with embedded python files.

For maint-3.8 the issue is different, but in a similar vein: the file_path passed to the HierBlockGenerator is ignored in lieu of the `platform.config.hier_block_lib_dir` variable which can be set, confusingly, by the GRC_HIER_PATH env var (perhaps this changed from when the OP looked at this, the docstring is also wrong). And as mentioned in the OP, yml file is _always_ put in that `hier_block_lib_dir`.

In addition, there's a [line in grc/compiler.py](https://github.com/gnuradio/gnuradio/blob/a152662f8536a1f389f7f799f588a0e4623a7bea/grc/compiler.py#L48)
that references a `save_to_lib` attribute that I can't find anywhere else in the code. It could probably be removed.

I would propose changing the env var and attribute to be the same (either hier_block_lib_dir or grc_hier_path), removing the save_to_lib in compiler.py (which will error out if the output dir does not exist), adding back the `file_path` parameter as `output_dir` (to be consistent with other code) probably defaulting to None, and ensuring that both the .py and .yml file are written to the given `output_dir` (or grc_hier_path if None).

**Comment by dkozel** [comment]
I believe the PR https://github.com/gnuradio/gnuradio/pull/4871 closes this issue.
