### ISSUE TITLE
Remove `snprintf` usage

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2875]
List of files that detect and/or us snprintf:
{{{
./gnuradio-runtime/ConfigChecks.cmake
./gnuradio-runtime/lib/vmcircbuf_mmap_shm_open.cc
./gnuradio-runtime/lib/vmcircbuf_mmap_tmpfile.cc
./gnuradio-runtime/lib/local_sighandler.cc
./gr-vocoder/lib/freedv_tx_ss_impl.cc
}}}
How about let's fix them all, to totally purge this evil from our midst!

**Comment by michaelld** [comment]
oh yes let's please !

**Comment by btashton** [comment]
@marcusmueller I'll throw together the PR. I think vocoder is the only one still using it, the rest just need the macros removed. 

The vocoder one if I remember is more complicated because there is a struct with a allocated buffer passed around and I was not sure how that was being used which is why I did not include it in the first patch.

**Comment by argilo** [comment]
Re-opening, since #3817 and #3834 haven't been merged yet.
