### ISSUE TITLE
gr3.7/3.8 | Constellation modulator | data gets shifted

### ISSUE THREAD

**Issue by fmagno** [gnuradio/gnuradio#2920]
Data is shifted (rotated) after going through a `constellation modulator`.

Input data: 0b**00001111**
output data: 0b**00111100**

![image](https://user-images.githubusercontent.com/3079603/69377257-d0c51180-0ca3-11ea-9b34-7dea5e045dcd.png)

Could this be an (un)expected effect of the RRC filter?

```python
generic_mod(gr.hier_block2):
(...)
# pulse shaping filter
        nfilts = 32
        ntaps = nfilts * 11 * int(self._samples_per_symbol)    # make nfilts filters of ntaps each
        self.rrc_taps = filter.firdes.root_raised_cosine(
            nfilts,          # gain
            nfilts,          # sampling rate based on 32 filters in resampler
            1.0,             # symbol rate
            self._excess_bw, # excess bandwidth (roll-off factor)
            ntaps)
        self.rrc_filter = filter.pfb_arb_resampler_ccf(self._samples_per_symbol,
                                                       self.rrc_taps)
(...)
```

**Comment by mormj** [comment]
I've run across a similar problem, in that the group delay of the rrc filter gets added in after the constellation modulator.  The hack workaround I had used is to put a skip head after the constellation modulator so that it syncs up with the stream mux.  

The question I have here (and similar issues exist in the gr-digital corr_est example with modulate_vector) is whether the output of these blocks should be automatically truncated to align the bits with the output signal - and I'm not sure for this one the answer is yes.  I think the gr-digital corr_est example is worse because it returns a truncated (at the end) modulated vector, when you would expect a time centered modulated waveform.
