### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by catalinalb** [gnuradio/gnuradio#3013]
Help Please!

I am running Ubuntu 18.04 and I did installed gnuradio 3.7 over pybombs and pybombsgui.

I am running into this error when I want to use gr-fosphor:

Executing: /usr/bin/python2 -u /home/ctl/Desktop/Catalin/GNU radio/top_block.py

  File "/home/ctl/Desktop/Catalin/GNU radio/top_block.py", line 157
    self.fosphor_qt_sink_c_0 = Template error: #set $win = 'self._%s_win'%$id
                                            ^
SyntaxError: invalid syntax

>>> Done (return code 1)

**Comment by devnulling** [comment]
hi @catalinalb

This is probably due to the current head of gr-fosphor is for GR 3.8. https://github.com/gnuradio/gr-recipes/blob/master/gr-fosphor.lwr#L25

I would suggest to switch the gr-fosphor recipe to use either the gr3.7 or gr3.7-qt5 branch.


I'm going to close this issue, questions such as this are better served either on the mailing list [0], on Slack (register here [1] and login here [2]), or on IRC [3].

[0] - https://wiki.gnuradio.org/index.php/MailingLists
[1] - https://slack.gnuradio.org/
[2] - https://gnuradio.slack.com/
[3] - https://wiki.gnuradio.org/index.php/IRC
