### ISSUE TITLE
Fix unicode handling in YAML files

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3209]
5de869ec0b7ef660d052ce7c0b86cd9d5eaadc2d is a bad fix (we need to fix it, even English literature usually says "Mueller and Muller"), but it highlights an underlying issue.

I fought to be able to write my last name in the flowgraph author field in the Options block. Don't disrespect my name, darn, GNU Radio!

**Comment by japm48** [comment]
I just reverted 5de869e, and, apparently, it works on my machine (TM), no trace of #2985.

I suspect it's because of python 3 (more context: arch, Gnome 3.36, pyaml 20.4.0-1, python-gobject 3.36.0).

Proof:
![umlaut](https://user-images.githubusercontent.com/1911407/78952154-ead98200-7ad4-11ea-9d91-b02760c74a85.png)
![umlaut2](https://user-images.githubusercontent.com/1911407/78952576-553ef200-7ad6-11ea-96fa-18e25785902c.png)

**Comment by marcusmueller** [comment]
seems to be solved
