### ISSUE TITLE
max output buffer set error

### ISSUE THREAD

**Issue by chrkyl** [gnuradio/gnuradio#3228]
I am new to gnuradio.  I am trying to use it with Trunk Recorder and when I run the program I am getting the following error:
gr::log :WARN: flat_flowgrap - Block (multiply_cc8) max output buffer set to 807424 instead of requested 4096
terminate called after throwing an instance of 'std::runtime_error'
what(): problems allocating a buffer with the given max output of buffer constraint!
Aborted (core_dumped)

Anyone have any ideas where I am going wrong?

**Comment by michaelld** [comment]
(1) There is a block called "multiply_cc" -- looks like complex stream x stream multiply -- where the output buffer size is set -way- too high ... might be due to an edit someone put in place to set the min buffer size ... but, who knows since we can't see the flowgraph!

(2) There is -very- little chance that this is an actual issue with GNU Radio. A -much- better venue would be the GR discussion list: https://lists.gnu.org/mailman/listinfo/discuss-gnuradio

I'm closing this issue.

You can followup with me directly if you want: michael.dickens@ettus.com ... I'll help out as best I can ... but there's not much more I can say without seeing your flowgraph ... meaning the GRC / Python version, not a screenshot of it.
