### ISSUE TITLE
Can FX8010/Emu10k1/Emu10k2/Emu20k1 DSP be used anyhow?

### ISSUE THREAD

**Issue by KOLANICH** [gnuradio/gnuradio#3231]
Soundcards by Creative Technology contain a DSP. Multiple DSP programs can be loaded and linked into a DAG. Signal processed with DSP programs (called `patches`) can be captured back. It is also possible process signals from physical inputs or/and output tye result to physical outputs.

https://github.com/alsa-project/alsa-tools/tree/master/as10k1 - assembler + instruction format docs. Though it may make sense to write an LLVM backend, there are only 16 opcodes.
https://github.com/alsa-project/alsa-tools/tree/master/ld10k1 - loader and linker
https://github.com/kxproject/kx-audio-driver - more sophisticated software with GUI, built-in filters, but for Windows.
https://github.com/kxproject/kX-Audio-driver-Documentation - docs and tutorials, including the docs to the chips.

**Comment by marcusmueller** [comment]
This is more of a question, not a source code issue. To answer it would take a bit of a broader reply, which we really shouldn't be trying to put into a bug tracker. You know what? Please sign up for the [discuss-gnuradio](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio) mailing list and ask there – it'd also be good if you could explain what you want to *achieve*, because honestly, it's not clear.
