### ISSUE TITLE
GR links missing or brokens in GR Tutorials

### ISSUE THREAD

**Issue by f6bvp** [gnuradio/gnuradio#3514]
Trying to learn practicing GR following tutorial 7 that is 6 years old  I found a number of broken links.
For example in this page : https://github.com/gnuradio/gr-tutorial/tree/master/examples
this klink is broken : _http://gnuradio.org/redmine/projects/gnuradio/wiki/TutorialsTaskForce_
The same in README file for the same tutorial 7.
In addition, wiki https://wiki.gnuradio.org/index.php/Guided_Tutorial_PSK_Demodulation link toward mpsk_stage1.grc example flowgraph is missing.
However, the most annoying is that flowgraphs are based on HTML (XML) format not compatible with GNU Radio 3.8.
I wonder if gr_modtool could be used in order to convert grc flowgraphs into yaml files ? 
However there is no example for that and as a beginner I don't know how to perform that task.
Could someone help ?
Bernard
(hamradio f6bvp, most interested in gr-satellites by Daniel Estévez)

**Comment by dkozel** [comment]
Hello Bernard.

Unfortunately the `gr-tutorials` repository has been unmaintained for, as you note, 6 years. So far no one has volunteered to update them. The Guided Tutorials on the wiki are mostly updated but the PSK one has been left to the end due to it's size and complexity. Barry KV4FV has been doing tremendous work bringing the tutorials up to date.

GNU Radio 3.8 will automatically convert an XML flowgraph from 3.7 into the new YAML format, just open the grc file with GNU Radio Companion. I've done this myself with a few of the gr-tutorials flowgraphs.

The best place to ask for assistance with GNU Radio, the tutorials, or third party modules like gr-satellites is the chat channel (https://chat.gnuradio.org) or the mailing list.
https://wiki.gnuradio.org/index.php/MailingLists

Cheers, Derek
MW0LNA
