### ISSUE TITLE
How can I downgrade from 3.8 to 3.7?

### ISSUE THREAD

**Issue by ccskying** [gnuradio/gnuradio#3666]
As I said in the title, I'm trying to downgrade from 3.8 to 3.7 in order to run old python2 code.
I use the following command:
```
sudo apt-get --purge remove gnuradio
sudo add-apt-repository --remove ppa:gnuradio/gnuradio-releases
sudo add-apt-repository --remove ppa:gnuradio/gnuradio-master
sudo add-apt-repository ppa:gnuradio/gnuradio-releases-3.7
sudo apt-get update
sudo apt-get install gnuradio
```
But I still  get gnuradio 3.8

What mistake did I make?

**Comment by jdemel** [comment]
You use `apt` thus you probably use a debianoid distribution. The exact version would be required to properly answer your question properly. I suspect your distro repositories provide a GR 3.8 package. `apt` installs the package with the highest version string, in this case GR 3.8 apparently.
Since python2 is effectively dead since 2020-01-01, it would probably be favorable to move your python code to python3 instead of a GR downgrade. In case this is supposed to be a quick test you may be better off with e.g. a Docker container.

**Comment by dkozel** [comment]
@ccskying I would guess that you're on Ubuntu 20.04 which has GNU Radio 3.8 in it's repository and that Apt is using the newer release by default. You can look into manually selecting in apt which package to install.

If you try this and have more questions please join us in the chat as that's a much better place to answer questions.
https://chat.gnuradio.org
