### ISSUE TITLE
How to run a block at a time interval?

### ISSUE THREAD

**Issue by guokr321** [gnuradio/gnuradio#3711]
For example, send a packet to USRP Sink every 30 ms.

**Comment by dkozel** [comment]
Hi @guokr321,
There are (at least) two ways to transmit a packet every 30 ms. One is to create burst transmissions with start and end of burst tags attached and time tags instructing the USRP driver to start the transmission at 30 ms intervals. Or you can stream continuously and add zeros between the packets so that they start 30ms apart.

I suggest reading the UHD manual page on timed commands and the GNU Radio documentation on custom blocks and tags.
https://kb.ettus.com/Synchronizing_USRP_Events_Using_Timed_Commands_in_UHD
https://wiki.gnuradio.org/index.php/Tutorials
https://wiki.gnuradio.org/index.php/Guided_Tutorial_Programming_Topics#Stream_Tags

If you have questions once you get started then the chat channel or email list are better places to find help. The USRP Users email list is also a really good place for questions about USRPs. I hope you get your application working.
https://chat.gnuradio.org
https://wiki.gnuradio.org/index.php/MailingLists
