### ISSUE TITLE
python crashes

### ISSUE THREAD

**Issue by gotchicode** [gnuradio/gnuradio#3803]
Hi,

I try to launch the resampler_demo.grc and python crashes after clicking execute.

I am on Windows 7, and use GNU 3.8.1

Thanks

![gnu](https://user-images.githubusercontent.com/65652807/95025810-d691ce80-068c-11eb-81f1-a3e993071192.jpg)

![image](https://user-images.githubusercontent.com/65652807/95025824-eb6e6200-068c-11eb-87c6-41c31b1ba2af.png)

**Comment by MattMills** [comment]
@gotchicode  Since you're on Windows and you're seeing the same return code (-1073741795) I'd bet you are seeing the same issue as #3822. There is a suggested fix I put in that issue you may want to try and see if it resolves your issue.

**Comment by gvanem** [comment]
I'm on Windows too. The sample works fine with the latest 3.9 master AFAICS. Compiling and running it I get this:
![resampler_Demo](https://user-images.githubusercontent.com/945271/99508896-6a8dd000-2985-11eb-94e7-69033c400591.png)

**Comment by nickoe** [comment]
Assuming this is really a packaging issue by gnieboer as seen in https://github.com/gnieboer/GNURadio_Windows_Build_Scripts/issues/48 and maybe @gnieboer has not bee able to make a build because of https://github.com/gnuradio/gnuradio/issues/3911. 

I will close this ticket as it can be tracked the other issues.
