### ISSUE TITLE
Fix qa_ofdm_chanest_vcvc

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#4102]
That unit test likes to fail in a lot of places, and curiously, it started happening to me after checking in a change to `add_block`. Barring strange quantum stuff, there's something fishy going on with FPU state, maybe?

**Comment by mormj** [comment]
The chanest test case that is failing looks like this:
![image](https://user-images.githubusercontent.com/34754695/105077113-04432d80-5a5a-11eb-8ecd-c861d7a10272.png)

and it is failing because there are no tags in the vector sink

The vector source block only makes one work call - none of the other blocks make it to a work call, and it is the vector source that signals done.  

If I remove the noise and add blocks, the test works fine.  I'm thinking that the difference in item sizes (32 len vector vs single complex for the noise source) has confused the scheduler and it doesn't figure out in time how to get items to the noise source before everyone heard that the vector source was completed.  Definitely an issue in the scheduler, but not something that should be caught by this test case.

The other way to "fix" this is to make the vector source repeat and put a head at the end:

![image](https://user-images.githubusercontent.com/34754695/105077975-4d47b180-5a5b-11eb-8d9a-486e0390c6ec.png)
