### ISSUE TITLE
how to use "swig"?

### ISSUE THREAD

**Issue by liumaolin-931** [gnuradio/gnuradio#4581]
How to use "swig" in GNURadio?Can all the C + + functions in a gr module be called by Python as long as they are the header files contained in the "swig" file? What tools should I use to write it?

**Comment by mormj** [comment]
@liumaolin-931 - **Please direct questions requiring general help to the discuss-gnuradio mailing list - https://lists.gnu.org/mailman/listinfo/discuss-gnuradio** 

Since this doesn't indicate a bug, issue, or feature request with the GR code itself, I'm closing it as a github issue.

In GR 3.8 and prior, the swig files get automatically populated for your block when you use gr_modtool.  you can edit the swig to add additional methods that are not part of your block.
In GR 3.9 and beyond, there is no more swig - we use pybind11 which is more explicit in what gets wrapped to python
