### ISSUE TITLE
Stream consumption feedback in USRP Sink using a token tag

### ISSUE THREAD

**Issue by kaushiksv** [gnuradio/gnuradio#4645]
**Feature**

I am a C.S. student trying to accomplish TC transmission with GnuRadio. [See Fig 7-2 here](https://public.ccsds.org/Pubs/231x0b3.pdf). I am required to modulate alternating 0s and1s and keep transmitting to hold the link, and modulate and transmit asynchronous messages as they arrive. I have written a throttled source block for this. However running it for several hours results in dozens of underruns. So a feedback based rate/latency control is better.

I have implemented a very simple addition to USRP sink block that will send out a message when it sees a a tag with a specified key. This msg is used by the source block to to keep track of number of tokens in flight, and control the output rate/latency.
More info: https://www.youtube.com/watch?v=jq0RewceCwc

![Screenshot_20210522_131855](https://user-images.githubusercontent.com/4756704/119225006-ea018500-bb09-11eb-9f71-10130e8c1c0f.png)

As this is something concerning timing, I think it deserves a seperate output message port (hidden when tag name is missing; default)

If this is a fairly common use case, I would love to create a PR.

Thanks.

**Comment by willcode** [comment]
A throttled source and a hardware sink (throttled by its own clock) will eventually give you over/underruns, since the two clocks do not necessarily match.

The links above are to a standards document and a GRCon talk by Matt Ettus, and it is unclear from the description above what you have done. My guess is that the logic you have implemented should be in a separate block, not in the USRP Sink.

If you have some code you think would be of use to everyone, then please do make a PR and the discussion can move to the PR.

For general discussion, the mailing list or chat.gnuradio.org are good. Let's close this issue, since this is not a problem or feature request.
