### ISSUE TITLE
Flowgraph doesn't update disabled blocks properly if samp_rate is controlled by another variable

### ISSUE THREAD

**Issue by solomonbstoner** [gnuradio/gnuradio#4788]
Bug found by @drmpeg. Related to Issue #4781, except this is specific to disabled blocks. 

Download [this flowgraph](http://www.w6rz.net/samptest.grc). There are two variables, `symbol_rate` and `samp_rate`. `samp_rate = symbol_rate * 2`. 

#### Expected behavior
When the `symbol_rate` is changed, and `Apply` is pressed, the flowgraph should reflect the new `samp_rate` for all blocks.

#### Actual behavior
The following behaviors were noted:
1. Pressing just the `OK` button doesn't update the disabled block. Either that or there's a lag in the updating. For example, setting symbol_rate to 40e3 at first and pressing Ok wouldnt update the disabled block to 80e3. But after I re-set symbol_rate to 50e3 and press Ok, the disabled block gets set to 80e3.
2. `Apply` updates the disabled block, but only after `OK` is clicked. 
3. Pressing `Apply` + `Cancel` doesnt update the disabled block for some reason (while the enabled blocks are updated). 

Everyone is welcome to try out that flowgraph and report any other unexpected behaviors. It helps us narrow down the cause :)

**Comment by dl1ksv** [comment]
I can reproduce this behaviour.
But what is the expected behaviour?
Should disabled blocks be updated if enabled blocks are updated or should the be untouched.

If I open this flowgraph in grc the disabled throttle displays:
Sample Rate: samp_rate.
That means the the value is not evaluated.  But open and close a block forces the disabled block to evaluate it's value.

My proposal: Do not evaluate disabled blocks until they will be enabled

**Comment by solomonbstoner** [comment]
Nice! Thanks for resolving the issue :)
