### ISSUE TITLE
Clean up pyqtwidget(), sip wrappers

### ISSUE THREAD

**Issue by willcode** [gnuradio/gnuradio#4857]
@Yamakaja pointed out a possible small memory leak where various qt widgets return an opaque handle as a python object
```
#ifdef ENABLE_PYTHON
PyObject* number_sink_impl::pyqwidget()
{
    PyObject* w = PyLong_FromVoidPtr((void*)d_main_gui);
    PyObject* retarg = Py_BuildValue("N", w);
    return retarg;
}
#else
void* number_sink_impl::pyqwidget() { return NULL; }
#endif
```
which is then wrapped by PyBind11
```
        .def(
            "pyqwidget",
            [](std::shared_ptr<number_sink> p) {
                return PyLong_AsLongLong(p->pyqwidget());
            },
            D(number_sink, pyqwidget))
```
but does not deallocate the object returned by `pyqwidget()`. This brings up the question of why we are going through all this trouble to return a `long long`. The end user of this value is SIP, for instance in block template code
```
        ${win} = sip.wrapinstance(self.${id}.pyqwidget(), Qt.QWidget)
```
where SIP is wrapping the custom widgets for Python.

Can this be simplified?

**Comment by Yamakaja** [comment]
So this is a bit of an awkward situation because we're passing a pointer from C++ to python using pybind11, and then passing that back to SIP, another python <-> native wrapper, though i'm not sure what you'd go about simplifying this. Could we maybe return the wrapper directly?

The obvious first step here would be to replace that leftover python stuff with either a `void *pyqwidget();` or `uintptr pyqwidget();`, where the latter has the added benefit of not requiring a pybind trampoline.
