### ISSUE TITLE
grc: add working example project

### ISSUE THREAD

**Issue by d33tah** [gnuradio/gnuradio#5417]
### Feature Description

When experimenting with GRC for the first time, it's not easy to see if it "works". My idea of a hello world was a signal / noise generator hooked up to an audio sink, audibly letting me know whether things actually execute. The problem I had was that the defaults for those blocks were not trivially compatible with audio sink:

* the maximum of noise generator should be "2G", not "2", because otherwise nothing audible gets generated,
* the output type for signal generator should be "int", because "complex" is not compatible with what audio sink expects.

The first one was not easy to debug - I knew nothing about GRC and didn't even know if it would work on my system. What would have help is a quick access to an example "hello world" project - something accessible through the menu that has it ready to execute. Having a collection of such working examples could be a nice way for GRC to be self-documenting, displaying major features in a way that makes it easy to experiment with.

### Feature Urgency

medium (would be nice to have in the near future)

**Comment by marcusmueller** [comment]
> * the maximum of noise generator should be "2G", not "2", because otherwise nothing audible gets generated,
> * the output type for signal generator should be "int", because "complex" is not compatible with what audio sink expects.

(aside from 2G making no sense, specifically, because it's not valid, and the audio sink by default also not taking ints,)

No. Very few of the blocks in GNU Radio are "one-trick ponies". The current defaults makes sense in a lot of setting!

Only because the example you consider to be a good first example would want other defaults, these aren't "good" defaults in the general case! For example, GNU Radio is a software defined radio framework. The "default" data type for a signal source hence is complex – because complex baseband is what software defined radio deals with, most of the time.

> Having a collection of such working examples could be a nice way for GRC to be self-documenting, displaying major features in a way that makes it easy to experiment with.

You'll find a big collection of examples that came with your GNU Radio installation. However, I'll put stress on *find*, because you do need to look for them.

I'll close this issue, as its default suggestions are really not something viable, but let's not drop the ball on the overarching issue here: 

1. you seemingly were not directly able to find https://tutorials.gnuradio.org from within GRC
2. the examples that come with GNU Radio aren't easily found, nor are they "sorted" by suitability for beginners

Personally, I think you're overestimating the usefulness of an example without explanation – as you can see, I've got a wildly different idea of what a reasonable default is than you! We need examples, more present in GRC, but we already have a lot – in the tutorials, and installed alongside with GNU Radio.
