### ISSUE TITLE
Build error in video-sdl

### ISSUE THREAD

**Issue by kiufta** [gnuradio/gnuradio#6164]
### What happened?

```
[ 22%] Linking CXX shared library libgnuradio-video-sdl.so
mold: fatal: SDL_dummy_main.c.o: not claimed by the LTO plugin; please make sure you are using the same compiler of the same version for all object files
collect2: error: ld returned 1 exit status
```

### System Information

OS: Arch
GR Installation Method: from source, linker: mold

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

cmake
make

**Comment by willcode** [comment]
Assuming you were building GNU Radio when this happened, this looks like an ABI or ELF format mismatch in the build environment. Maybe your compiler and the SDL libraries don't get along. You'll probably figure this out faster if you close this issue and ask for help on chat.gnuradio.org or the mailing list. I'm going to close this, since it's not likely to be a bug, but please re-open and add more information if you think it is.
