### ISSUE TITLE
Make installation under MACOS easier 

### ISSUE THREAD

**Issue by AndySymons** [gnuradio/gnuradio#6678]
### Feature Description

When installing gnuradio-companion on Mac OSX 10.15.7 (Catalina) I found no single best method, and a lot of postings with various ways of doing it. 

Ideally I would like a .pkg or .dmg package that installs itself like any other Macos app. If I have to do it via Terminal, as least it should be straightforward, using one preferred method (ports), include all dependencies, and be robust, with usable error messages when it goes wrong. 

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

The biggest issue I had is that it installs incorrectly it there is any Python version higher than 2.7 on the machine. In my case it installed under Python 3.9 even after I set Python 2.7 as the default. It should automatically pick the right one. I had to copy it by hand. I had to take several steps to set PYTHONPATH and LD_LIBRARY_PATH manually - this should not be necessary. 

After all that it still complains about a missing schema “org.gnome.desktop.interface” 
and NameError("name 'cpmmod_bc_make_gmskmod_bc' is not defined") 
... without explaining what they are or how I can fix them

**Comment by marcusmueller** [comment]
Hi Andy!

Making it easy to install GNU Radio has a high priority, already. However, addressing what you request specifically:
https://wiki.gnuradio.org/index.php?title=InstallingGR has a single recommended method, and we also have quite successful Anaconda packaging :)

Installation via dmg makes little sense, GNU Radio is first and foremost a library; while GRC + the GNU Radio underpinnings of it is a useful tool for many, it's not a closed ecosystem, and we really don't fit into that kind of packaging all to well!

GNU Radio is no longer compatible with Python 2 (hasn't been for quite some time), and it's inherently been built against a specific version of the Python library, so you cannot "force" any version, that's not how it works ;)

Hence: Since what is dear to your heart is also ever-present in our minds (to use a bit of overly poetic devices there), I'm closing this bug report.

**Comment by AndySymons** [comment]
Thanks for the clarity and recommended method
