### ISSUE TITLE
improve samplerate by buffer

### ISSUE THREAD

**Issue by SEU-zhc** [gnuradio/gnuradio#6691]
### Feature Description

Can I use a custom module with USRP to buffer the data received from radar waves within a 100ms window, and then stop transmitting and receiving? During the remaining 900ms, can I sample the buffered data to improve the sampling rate for that 100ms time window?
In an ideal scenario, assuming USRP supports a sampling rate of 1MHz, this would allow for a maximum sampling rate of 1MHz * 10.

### Feature Urgency

low (just an idea)

**Comment by marcusmueller** [comment]
This doesn't seem to be a feature request for GNU Radio but a general question on how specific hardware works, which is independent of GNU Radio. So, I'm closing this as invalid. Generally, such discussion is welcome on the discuss-gnuradio mailing list, though! 

To safe you repeating the question on there and getting a negative response, I'll quickly reply here (please do not start a discussion here, it's an issue tracker):

10 MS/s is a low sampling rate, all USRPs support it out of the box anyway. You don't have to do anything for that.

For relevantly high sampling rates (say, 250 MS/s instead of a maximum of 25 MS/s), 100ms means millions of samples, so your SDR would need to buffer literally dozens of Megabytes in itself. SDRs typically can't do that, so for high rates, what you want is even theoretically impossible.
