### ISSUE TITLE
gr_modtool: c++ blocks: enabling C++ QA gen leads to broken lib/CMakeLists.txt

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#7131]
### What happened?

investigating #6960, I found that with noblock, sync, hier and  probably all other block types, gr_modtool breaks CMakeLists.txt

### System Information

OS: Linux, source build

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-649-gd7cdf222

### Steps to Reproduce the Problem

```shell
#!/bin/sh
modname="foobar"
blockname="nothing"
blocktype="hier"
rm -r "gr-${modname}"
gr_modtool newmod "${modname}"
cd gr-"${modname}"
gr_modtool add --add-cpp-qa --block-type "${blocktype}" --copyright dontcare --lang cpp "${blockname}"
mkdir build
cd build

cmake ..
```

The offending lines in lib/CMakeLists.txt are:

```cmake
  50   │ ########################################################################
  51   │ # Build and register unit test
  52   │ ########################################################################
  53   │ include(GrTest)
  54   │
  55   │ # If your unit tests require special include paths, add them here
  56   │ #include_directories()
  57   │ # List all files that contain Boost.UTF unit tests here
  58   │ list(APPEND test_foobar_sources)
  59   │ qa_nothing.cc
  60   │ # Anything we need to link to for the unit tests go here
  61   │ list(APPEND GR_TEST_TARGET_DEPS gnuradio-foobar)
  62   │
  63   │ if(NOT test_foobar_sources)
  64   │     message(STATUS "No C++ unit tests... skipping")
  65   │     return()
  66   │ endif(NOT test_foobar_sources)
  67   │
  68   │ foreach(qa_file ${test_foobar_sources})
  69   │     gr_add_cpp_test("foobar_${qa_file}" ${CMAKE_CURRENT_SOURCE_DIR}/${qa_file})
  70   │ endforeach(qa_file)
```

### Relevant log output

```shell
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.6") found components: doxygen dot
CMake Error at lib/CMakeLists.txt:59:
  Parse error.  Expected a command name, got unquoted argument with text
  "qa_nothing.cc".


-- Configuring incomplete, errors occurred!
```

**Comment by vnydv21** [comment]
@marcusmueller 
Also, isn't removing the `qa_<block_name>.cc` files from `lib` directory after `gr_modtool rm <block_name>` the expected behaviour? :/
- [ ] It seems like the `rm` isn't doing that! (I guess these lines are having the issue... (no match for qa_*.cc ) https://github.com/gnuradio/gnuradio/blob/52889c8a5cd69ea1ef8efb69576dbf99d73e9c86/gr-utils/modtool/core/rm.py#L151-L170

- [ ] Trying resolving the current issue first. (the closing bracket must be after `qa_*.cc`)

interestingly, other issues are also there like,
- [ ] `GR_ADD_TEST` in `python/bindings/` aren't got removed after `rm`
- [ ] same as above but with `qa_*.cc` in `lib/CMakeList.txt`
