### ISSUE TITLE
QtGUI time sink and skip head using range

### ISSUE THREAD

**Issue by le0nidus** [gnuradio/gnuradio#7373]
### What happened?

When applying to the signal skip head or/and head block (and change the values through range block) the plot won’t update

### System Information

OS: Windows
GR Installation Method: radioconda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10

### Steps to Reproduce the Problem

Generate signal with 1M samples
Place range block to control the skip head block
Connect it to the qtgui time sink block and generate the flowgraph
The slider doesn’t change the plot, you’ll see the plot starting from the default value which is stated in the range block

**Comment by willcode** [comment]
It sounds like you are trying to update the Head value at runtime. This is not possible, since the value for the Head block is set when the flowgraph runs, and there would be no purpose in changing it. The offset is a number of samples since the flowgraph started. The flowgraph is not re-run when the range is changed at runtime. If this is not clear please use chat.gnuradio.org (General Chat) or the mailing list for further help.
