### ISSUE TITLE
Filter design tool doesn't open

### ISSUE THREAD

**Issue by jc5706** [gnuradio/gnuradio#7543]
### What happened?

GNU radio companion v3.10.9.2 installed on Ubuntu 24.04
When clicking on Tools > Filter Design Tool, nothing happens. No crash but nothing opens

### System Information

OS: Ubuntu 24.04 (on VM)
GR Installation Method: apt install

### GNU Radio Version

3.9  (maint-3.9)

### Specific Version

3.9.10.2

### Steps to Reproduce the Problem

open GNU Radio companion
Click on Tools > Filter design tool

**Comment by marcusmueller** [comment]
Thanks for the report! I've been able to reproduce:

```
Traceback (most recent call last):
  File "/usr/bin/gr_filter_design", line 15, in <module>
    filter_design.main(sys.argv)
  File "/usr/lib/python3/dist-packages/gnuradio/filter/filter_design.py", line 2375, in main
    gplt = gr_plot_filter(options)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/filter/filter_design.py", line 114, in __init__
    self.gui.setupUi(self)
  File "/usr/lib/python3/dist-packages/gnuradio/filter/pyqt_filter_stacked.py", line 71, in setupUi
    self.freqPlot = GrFilterPlotWidget(self.freqTab)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/filter/GrFilterPlotWidget.py", line 7, in __init__
    PlotWidget.__init__(self, parent, background,
  File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/PlotWidget.py", line 54, in __init__
    GraphicsView.__init__(self, parent, background=background)
  File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/GraphicsView.py", line 61, in __init__
    QtWidgets.QGraphicsView.__init__(self, parent)
TypeError: arguments did not match any overloaded call:
  QGraphicsView(parent: Optional[QWidget] = None): argument 1 has unexpected type 'QWidget'
  QGraphicsView(scene: Optional[QGraphicsScene], parent: Optional[QWidget] = None): argument 1 has unexpected type 'QWidget'
```
and I've been able to fix by applying what was done in #7088.

The good news is that the fix was already applied to the GNU Radio 3.10 release series. It's in 3.10.10.0, the release directly *after* the release you're using (which is what Ubuntu ships).

There's a quick fix: swap the first two lines of /usr/lib/python3/dist-packages/gnuradio/filter/CustomViewBox.py .

Ideally, however, Ubuntu would go and take the never version. Don't know about their policy regaring versions of packages after they did an LTS release – but if we don't tell Ubuntu, they probably won't do an update to fix that for everyone. 

Would you want to file a bug on Ubuntu's bug platform, launchpad? Process of that is described [here](https://help.ubuntu.com/stable/ubuntu-help/report-ubuntu-bug.html.en).  Ideally you just say "trace and solution at https://github.com/gnuradio/gnuradio/issues/7543 ; ubuntu might need to update the gnuradio package", or something.
