### ISSUE TITLE
Bit disappearance bug in GNURadio OFDM demo

### ISSUE THREAD

**Issue by flow233-ai** [gnuradio/gnuradio#7574]
### What happened?

When I transmit a csv file, some of the bits in a csv file are lost, resulting in the original table size not being the same as the transferred table size. Is this a bug or is it because some of my parameters like sample rate are not set correctly.

### System Information

OS: LINUX
GR Installation Method: source

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.2.0

### Steps to Reproduce the Problem

Open the GNURadio example file, which is named 'OFDM_loopback.grc'.
Then transmit a predefined txt file and also record the output file.

**Comment by marcusmueller** [comment]
Hi! The 3.8 is out of scope for bugs being fixed in the OFDM demo, because since then we already changed a lot of components of these example flow graphs.

Hence, when you update your GNU Radio to a recent version, you will not have the same problem. If you do, please let us know. (You should *not* be using GNU Radio 3.8, and considering you say you compiled it from source, it's really very surprising you chose this outdated version. A lot of the bugs that people might stumble upon have already been fixed since then; after all, we (me) tagged this version four and half a year ago!)
